# OpenSearch Operator + OpenSearch Cluster 배포
# opensearch-operator Helm 차트로 Operator 설치 후 OpenSearchCluster CR로 클러스터 생성
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - ../../base
  - opensearch-cluster.yaml
  - opensearch-dashboards-nodeport.yaml

helmCharts:
  - name: opensearch-operator
    repo: https://opensearch-project.github.io/opensearch-k8s-operator/
    version: "2.8.0"
    releaseName: opensearch-operator
    namespace: logging
    valuesFile: values.yaml
